spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql : true
        show_sql : true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug

csv:
  file-template: '%s_%s.csv'

#?????? ????? api??
corp-info:
  url: https://apis.data.go.kr/1130000/MllBsDtl_2Service
  endpoint: /getMllBsInfoDetail_2
  serviceKey: '%2BJlmGg9b7HFab38I1RWO6JGL5Zuq5NLQ6oRlzAmlEf9DEVKp6GAqRTX7hGdcM3Ogu10%2FL2gTMeeZ8NHqCJDLag%3D%3D'
  query-params:
    pageNo: '1'
    numOfRows: '1'
    resultType: 'json'

